version: '2'
services:
  app:
    build: .
    environment:
      - DB_USER=choredo
      - DB_PASSWORD=securelol
      - DB_DATABASE=choredo
      - DB_HOST=db
      - ENV=development
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=choredo
      - POSTGRES_USER=choredo
      - POSTGRES_PASSWORD=securelol